Line should own its data, don't pass socket around
Libera-Chat/haematite pull request #5
Opened 2022-07-05 18:33 UTC by jesopo

2022-07-05 21:24 UTC, TheDaemoness requested changes
Nice ideas here. I've tried to limit the review only to changes made in these commits. I have a few more questions that I'll ask separately.

2022-07-05 21:24 UTC, TheDaemoness commented on src/handler/ts6.rs
> +    args: Vec<String>,
If all you need is to use `args`'s values in a specific order, then this can be an `impl IntoIterator`, and the `VecDeque` below shouldn't be necessary, as you could use `let mut args = args.into_iter();` instead.

2022-07-05 21:24 UTC, TheDaemoness commented on src/handler/ts6.rs
> +            true => Some(args.pop_front().unwrap()),
If going the `impl IntoIterator` route, this `pop_front()` call would be changed to `next()`.

2022-07-05 21:24 UTC, TheDaemoness commented on src/handler/ts6.rs
> +                let args = line.args[3..line.args.len()].to_vec();
Consider `[3..]`.

2022-07-05 21:24 UTC, TheDaemoness commented on src/handler/ts6.rs
> +    fn handle(&mut self, network: &mut Network, line: Line) -> HandlerResult {
If `line` is still being borrowed everywhere it's used, it can still be a `&Line`.

2022-07-05 22:44 UTC, jesopo commented on src/handler/ts6.rs
> +    fn handle(&mut self, network: &mut Network, line: Line) -> HandlerResult {
is there a way to ask the linter to point out stuff like this? like an irritatingly nitpicky mode

2022-07-06 00:10 UTC, TheDaemoness commented on src/handler/ts6.rs
> +    fn handle(&mut self, network: &mut Network, line: Line) -> HandlerResult {
Yes: https://rust-lang.github.io/rust-clippy/stable/#needless_pass_by_value

You can change this lint to `warn` or `deny` using attributes in `main.rs`: https://github.com/rust-lang/rust-clippy#allowingdenying-lints

2022-07-06 00:29 UTC, TheDaemoness approved these changes

2022-07-06 10:03 UTC, merged